version: '3'

services:
  app:
    image: icddex/weather:latest
    volumes:
      - .:/artifact
    working_dir: /artifact
    ports:
      - 9000:9000
    depends_on:
      - postgres-db
      - composer
    networks:
      - content-weather
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
  composer:
    image: composer
    volumes:
      - .:/app
    command: install
    networks:
      - content-weather
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - 80:80
    working_dir: /artifact
    volumes:
      - .:/artifact
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - content-weather
  postgres-db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: dex
      POSTGRES_PASSWORD: d1
      POSTGRES_DB: meteo
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - content-weather
volumes:
  pgdata:
networks:
  content-weather: