version: '3'

services:
  web:
    image: nginx
    restart: always
    volumes:
      - .:/artifact
      - ./log:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    links:
      - php
      - db
  php:
    image: php:7.0-fpm
    restart: always
    volumes:
      - .:/artifact
  db:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_USER: dex
      POSTGRES_PASSWORD: d1
      POSTGRES_DB: meteo
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: